---
- name: deployment of cronjobs
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
    - name: Check if directory exists
      ansible.builtin.stat:
        path: "{{ backup_dir }}"
      register: dir_stat
      tags:
       - deploy
       - rollback

    - name: Show result if directory exists
      ansible.builtin.debug:
        msg: "Directory exists at {{ backup_dir }}"
      when: dir_stat.stat.exists and dir_stat.stat.isdir
      tags:
       - deploy
       - rollback

    - name: Ensure to create "{{ backup_dir }}" directory"
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      when: not dir_stat.stat.exists
      tags:
       - deploy
       - rollback

    - name: Get the hostname
      command: hostname
      register: custom_hostname
      tags:
       - deploy
       - rollback

    - name: Run crontab -l and allow errors
      ansible.builtin.command: crontab -l
      register: crontab_output
      failed_when: false
      tags:
       - deploy
       - rollback

    - name: Save crontab output to file (even if empty) for deployment
      ansible.builtin.copy:
        content: "{{ crontab_output.stdout | default('# No crontab for this user\n', True) + '\n' }}"
        dest: "deploy_crontab_{{ custom_hostname.stdout }}_before.txt"
        mode: '0644'
      tags:
       - deploy

    - name: Save crontab output to file (even if empty) for rollback
      ansible.builtin.copy:
        content: "{{ crontab_output.stdout | default('# No crontab for this user\n', True) + '\n' }}"
        dest: "rollback_crontab_{{ custom_hostname.stdout }}_before.txt"
        mode: '0644'
      tags:
       - rollback

    - name: Creates a cron job
      ansible.builtin.cron:
        name: "Log current date every minute"
        minute: "{{ CRON_MINUTE }}"
        hour: "{{ CRON_HOUR }}"
        day: "{{ CRON_DAY }}"
        month: "{{ CRON_MONTH }}"
        weekday: "{{ CRON_WEEKDAY }}"
        user: "{{ CRON_USER }}"
        job: "{{ CRON_JOB}}"
        state: present
      tags:
       - deploy

    - name: Removes a cron job
      ansible.builtin.cron:
        name: "Log current date every minute"
        minute: "{{ CRON_MINUTE }}"
        hour: "{{ CRON_HOUR }}"
        day: "{{ CRON_DAY }}"
        month: "{{ CRON_MONTH }}"
        weekday: "{{ CRON_WEEKDAY }}"
        user: "{{ CRON_USER }}"
        job: "{{ CRON_JOB}}"
        state: absent
      tags:
       - rollback

    - name: Post Deployment Verification
      ansible.builtin.command: crontab -l
      register: cronjobafter
      ignore_errors: true
      tags:
       - deploy
       - rollback

    - name: Save crontab output to file (even if empty) for deployment
      ansible.builtin.copy:
        content: "{{ cronjobafter.stdout | default('# No crontab for this user\n', True) + '\n' }}"
        dest: "deploy_crontab_{{ custom_hostname.stdout }}_after.txt"
        mode: '0644'
      tags:
       - deploy

    - name: Save crontab output to file (even if empty) for rollback
      ansible.builtin.copy:
        content: "{{ cronjobafter.stdout | default('# No crontab for this user\n', True) + '\n' }}"
        dest: "rollback_crontab_{{ custom_hostname.stdout }}_after.txt"
        mode: '0644'
      tags:
       - rollback
