# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ansible application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest ansible
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: ansible cronjob deployment
      run: |
        ansible-playbook -vvvvv cronjob_jobs.yaml --tags deploy

    - name: ansible cronjob deployment idempotent test
      run: |
        ansible-playbook -vvvvv cronjob_jobs.yaml --tags deploy
      continue-on-error: true
        
    - name: ansible cronjob rollback
      run: |
        ansible-playbook -vvvvv cronjob_jobs.yaml --tags rollback
      continue-on-error: true

    - name: ansible cronjob rollback idempotent test
      run: |
        ansible-playbook -vvvvv cronjob_jobs.yaml --tags rollback
      continue-on-error: true
